import {
    OrderDomain,
    OrderItemDomain,
    OrderAddressDomain,
    OrderStatusHistoryDomain,
    OrderPaymentDomain,
} from "../types";

export function toOrderItemDomain(dbItem: any): OrderItemDomain {
    return {
        id: dbItem.id,
        orderId: dbItem.orderId,
        sellerId: dbItem.sellerId,
        productId: dbItem.productId,
        variantId: dbItem.variantId,
        sku: dbItem.sku,
        variantSku: dbItem.variantSku,
        productSlug: dbItem.productSlug,
        productName: dbItem.productName,
        variantName: dbItem.variantName,
        brandName: dbItem.brandName,
        categoryName: dbItem.categoryName,
        thumbnailUrl: dbItem.thumbnailUrl,
        imageUrl: dbItem.imageUrl,
        snapshotSource: dbItem.snapshotSource,
        currency: dbItem.currency,
        unitPrice: dbItem.unitPrice ? Number(dbItem.unitPrice) : 0,
        compareAtPrice: dbItem.compareAtPrice ? Number(dbItem.compareAtPrice) : null,
        discountType: dbItem.discountType,
        discountAmount: dbItem.discountAmount ? Number(dbItem.discountAmount) : 0,
        taxType: dbItem.taxType,
        taxRate: dbItem.taxRate ? Number(dbItem.taxRate) : 0,
        taxAmount: dbItem.taxAmount ? Number(dbItem.taxAmount) : 0,
        quantity: dbItem.quantity ? Number(dbItem.quantity) : 0,
        subtotal: dbItem.subtotal ? Number(dbItem.subtotal) : 0,
        total: dbItem.total ? Number(dbItem.total) : 0,
        weight: dbItem.weight ? Number(dbItem.weight) : null,
        length: dbItem.length ? Number(dbItem.length) : null,
        width: dbItem.width ? Number(dbItem.width) : null,
        height: dbItem.height ? Number(dbItem.height) : null,
        inventoryLocation: dbItem.inventoryLocation,
        warehouseName: dbItem.warehouseName,
        fulfillmentType: dbItem.fulfillmentType,
        itemStatus: dbItem.itemStatus,
        sellerSku: dbItem.sellerSku,
        notes: dbItem.notes,
        createdAt: dbItem.createdAt instanceof Date ? dbItem.createdAt : new Date(dbItem.createdAt),
        updatedAt: dbItem.updatedAt instanceof Date ? dbItem.updatedAt : new Date(dbItem.updatedAt),
        deletedAt: dbItem.deletedAt ? (dbItem.deletedAt instanceof Date ? dbItem.deletedAt : new Date(dbItem.deletedAt)) : null,
    };
}

export function toOrderAddressDomain(dbAddress: any): OrderAddressDomain {
    return {
        id: dbAddress.id,
        orderId: dbAddress.orderId,
        addressType: dbAddress.addressType,
        recipientName: dbAddress.recipientName,
        phoneNumber: dbAddress.phoneNumber,
        addressLine1: dbAddress.addressLine1,
        addressLine2: dbAddress.addressLine2,
        landmark: dbAddress.landmark,
        city: dbAddress.city,
        district: dbAddress.district,
        state: dbAddress.state,
        postalCode: dbAddress.postalCode,
        country: dbAddress.country,
        latitude: dbAddress.latitude ? Number(dbAddress.latitude) : null,
        longitude: dbAddress.longitude ? Number(dbAddress.longitude) : null,
        deliveryNotes: dbAddress.deliveryNotes,
        createdAt: dbAddress.createdAt instanceof Date ? dbAddress.createdAt : new Date(dbAddress.createdAt),
    };
}

export function toOrderStatusHistoryDomain(dbHistory: any): OrderStatusHistoryDomain {
    return {
        id: dbHistory.id,
        orderId: dbHistory.orderId,
        sellerId: dbHistory.sellerId,
        changedByUserId: dbHistory.changedByUserId,
        fromStatus: dbHistory.fromStatus,
        toStatus: dbHistory.toStatus,
        action: dbHistory.action,
        source: dbHistory.source,
        result: dbHistory.result,
        reason: dbHistory.reason,
        remarks: dbHistory.remarks,
        referenceId: dbHistory.referenceId,
        ipAddress: dbHistory.ipAddress,
        userAgent: dbHistory.userAgent,
        changedAt: dbHistory.changedAt instanceof Date ? dbHistory.changedAt : new Date(dbHistory.changedAt),
        createdAt: dbHistory.createdAt instanceof Date ? dbHistory.createdAt : new Date(dbHistory.createdAt),
    };
}

export function toOrderPaymentDomain(dbPayment: any): OrderPaymentDomain {
    return {
        id: dbPayment.id,
        orderId: dbPayment.orderId,
        sellerId: dbPayment.sellerId,
        paymentNumber: dbPayment.paymentNumber,
        paymentStatus: dbPayment.paymentStatus,
        paymentMethod: dbPayment.paymentMethod,
        paymentGateway: dbPayment.paymentGateway,
        currency: dbPayment.currency,
        amount: dbPayment.amount ? Number(dbPayment.amount) : 0,
        gatewayFee: dbPayment.gatewayFee !== null ? Number(dbPayment.gatewayFee) : null,
        platformFee: dbPayment.platformFee !== null ? Number(dbPayment.platformFee) : null,
        taxAmount: dbPayment.taxAmount !== null ? Number(dbPayment.taxAmount) : null,
        netAmount: dbPayment.netAmount ? Number(dbPayment.netAmount) : 0,
        transactionId: dbPayment.transactionId,
        gatewayPaymentId: dbPayment.gatewayPaymentId,
        gatewayOrderId: dbPayment.gatewayOrderId,
        gatewayReferenceId: dbPayment.gatewayReferenceId,
        gatewaySignature: dbPayment.gatewaySignature,
        initiatedAt: dbPayment.initiatedAt ? (dbPayment.initiatedAt instanceof Date ? dbPayment.initiatedAt : new Date(dbPayment.initiatedAt)) : null,
        authorizedAt: dbPayment.authorizedAt ? (dbPayment.authorizedAt instanceof Date ? dbPayment.authorizedAt : new Date(dbPayment.authorizedAt)) : null,
        paidAt: dbPayment.paidAt ? (dbPayment.paidAt instanceof Date ? dbPayment.paidAt : new Date(dbPayment.paidAt)) : null,
        capturedAt: dbPayment.capturedAt ? (dbPayment.capturedAt instanceof Date ? dbPayment.capturedAt : new Date(dbPayment.capturedAt)) : null,
        failedAt: dbPayment.failedAt ? (dbPayment.failedAt instanceof Date ? dbPayment.failedAt : new Date(dbPayment.failedAt)) : null,
        cancelledAt: dbPayment.cancelledAt ? (dbPayment.cancelledAt instanceof Date ? dbPayment.cancelledAt : new Date(dbPayment.cancelledAt)) : null,
        expiredAt: dbPayment.expiredAt ? (dbPayment.expiredAt instanceof Date ? dbPayment.expiredAt : new Date(dbPayment.expiredAt)) : null,
        payerName: dbPayment.payerName,
        payerEmail: dbPayment.payerEmail,
        payerPhone: dbPayment.payerPhone,
        failureReason: dbPayment.failureReason,
        gatewayResponse: dbPayment.gatewayResponse,
        notes: dbPayment.notes,
        internalNotes: dbPayment.internalNotes,
        createdAt: dbPayment.createdAt instanceof Date ? dbPayment.createdAt : new Date(dbPayment.createdAt),
        updatedAt: dbPayment.updatedAt instanceof Date ? dbPayment.updatedAt : new Date(dbPayment.updatedAt),
        deletedAt: dbPayment.deletedAt ? (dbPayment.deletedAt instanceof Date ? dbPayment.deletedAt : new Date(dbPayment.deletedAt)) : null,
    };
}

export function toOrderDomain(dbOrder: any, items?: any[], addresses?: any[], history?: any[], payments?: any[]): OrderDomain {
    return {
        id: dbOrder.id,
        sellerId: dbOrder.sellerId,
        buyerId: dbOrder.buyerId,
        storeId: dbOrder.storeId,
        shippingAddressId: dbOrder.shippingAddressId,
        billingAddressId: dbOrder.billingAddressId,
        orderNumber: dbOrder.orderNumber,
        status: dbOrder.status,
        paymentStatus: dbOrder.paymentStatus,
        paymentMethod: dbOrder.paymentMethod,
        shippingMethod: dbOrder.shippingMethod,
        priority: dbOrder.priority,
        source: dbOrder.source,
        currency: dbOrder.currency,
        buyerName: dbOrder.buyerName,
        buyerEmail: dbOrder.buyerEmail,
        buyerPhone: dbOrder.buyerPhone,
        subtotal: dbOrder.subtotal ? Number(dbOrder.subtotal) : 0,
        discountAmount: dbOrder.discountAmount ? Number(dbOrder.discountAmount) : 0,
        couponDiscount: dbOrder.couponDiscount ? Number(dbOrder.couponDiscount) : 0,
        shippingCharge: dbOrder.shippingCharge ? Number(dbOrder.shippingCharge) : 0,
        taxAmount: dbOrder.taxAmount ? Number(dbOrder.taxAmount) : 0,
        grandTotal: dbOrder.grandTotal ? Number(dbOrder.grandTotal) : 0,
        isGift: dbOrder.isGift ?? false,
        giftMessage: dbOrder.giftMessage,
        requiresSignature: dbOrder.requiresSignature ?? false,
        sellerRemark: dbOrder.sellerRemark,
        internalRemark: dbOrder.internalRemark,
        expectedDeliveryDate: dbOrder.expectedDeliveryDate ? (dbOrder.expectedDeliveryDate instanceof Date ? dbOrder.expectedDeliveryDate : new Date(dbOrder.expectedDeliveryDate)) : null,
        actualDeliveryDate: dbOrder.actualDeliveryDate ? (dbOrder.actualDeliveryDate instanceof Date ? dbOrder.actualDeliveryDate : new Date(dbOrder.actualDeliveryDate)) : null,
        acceptedAt: dbOrder.acceptedAt ? (dbOrder.acceptedAt instanceof Date ? dbOrder.acceptedAt : new Date(dbOrder.acceptedAt)) : null,
        packedAt: dbOrder.packedAt ? (dbOrder.packedAt instanceof Date ? dbOrder.packedAt : new Date(dbOrder.packedAt)) : null,
        readyAt: dbOrder.readyAt ? (dbOrder.readyAt instanceof Date ? dbOrder.readyAt : new Date(dbOrder.readyAt)) : null,
        shippedAt: dbOrder.shippedAt ? (dbOrder.shippedAt instanceof Date ? dbOrder.shippedAt : new Date(dbOrder.shippedAt)) : null,
        deliveredAt: dbOrder.deliveredAt ? (dbOrder.deliveredAt instanceof Date ? dbOrder.deliveredAt : new Date(dbOrder.deliveredAt)) : null,
        cancelledAt: dbOrder.cancelledAt ? (dbOrder.cancelledAt instanceof Date ? dbOrder.cancelledAt : new Date(dbOrder.cancelledAt)) : null,
        returnedAt: dbOrder.returnedAt ? (dbOrder.returnedAt instanceof Date ? dbOrder.returnedAt : new Date(dbOrder.returnedAt)) : null,
        createdAt: dbOrder.createdAt instanceof Date ? dbOrder.createdAt : new Date(dbOrder.createdAt),
        updatedAt: dbOrder.updatedAt instanceof Date ? dbOrder.updatedAt : new Date(dbOrder.updatedAt),
        deletedAt: dbOrder.deletedAt ? (dbOrder.deletedAt instanceof Date ? dbOrder.deletedAt : new Date(dbOrder.deletedAt)) : null,
        
        items: items ? items.map(toOrderItemDomain) : undefined,
        addresses: addresses ? addresses.map(toOrderAddressDomain) : undefined,
        history: history ? history.map(toOrderStatusHistoryDomain) : undefined,
        payments: payments ? payments.map(toOrderPaymentDomain) : undefined,
    };
}
