import { OrderDomain, OrderItemDomain } from "../types";
import { 
    OrderListItemDto, 
    OrderListItemLineDto, 
    OrderDetailResponseDto, 
    OrderDetailAddressDto, 
    OrderDetailHistoryDto, 
    OrderDetailPaymentDto 
} from "../dto";

export function toItemLineDto(item: OrderItemDomain): OrderListItemLineDto {
    return {
        id: item.id,
        orderId: item.orderId,
        productId: item.productId,
        variantId: item.variantId,
        sku: item.sku,
        productSlug: item.productSlug,
        productName: item.productName,
        variantName: item.variantName,
        thumbnailUrl: item.thumbnailUrl,
        imageUrl: item.imageUrl,
        unitPrice: item.unitPrice.toFixed(2),
        quantity: item.quantity,
        total: item.total.toFixed(2),
    };
}

export function toOrderListItemDto(order: OrderDomain): OrderListItemDto {
    return {
        id: order.id,
        sellerId: order.sellerId,
        buyerId: order.buyerId,
        storeId: order.storeId,
        shippingAddressId: order.shippingAddressId,
        billingAddressId: order.billingAddressId,
        orderNumber: order.orderNumber,
        status: order.status,
        paymentStatus: order.paymentStatus,
        paymentMethod: order.paymentMethod,
        shippingMethod: order.shippingMethod,
        priority: order.priority,
        source: order.source,
        currency: order.currency,
        buyerName: order.buyerName,
        buyerEmail: order.buyerEmail,
        buyerPhone: order.buyerPhone,
        subtotal: order.subtotal.toFixed(2),
        discountAmount: order.discountAmount.toFixed(2),
        couponDiscount: order.couponDiscount.toFixed(2),
        shippingCharge: order.shippingCharge.toFixed(2),
        taxAmount: order.taxAmount.toFixed(2),
        grandTotal: order.grandTotal.toFixed(2),
        isGift: order.isGift,
        giftMessage: order.giftMessage,
        requiresSignature: order.requiresSignature,
        sellerRemark: order.sellerRemark,
        internalRemark: order.internalRemark,
        expectedDeliveryDate: order.expectedDeliveryDate ? order.expectedDeliveryDate.toISOString() : null,
        actualDeliveryDate: order.actualDeliveryDate ? order.actualDeliveryDate.toISOString() : null,
        acceptedAt: order.acceptedAt ? order.acceptedAt.toISOString() : null,
        packedAt: order.packedAt ? order.packedAt.toISOString() : null,
        readyAt: order.readyAt ? order.readyAt.toISOString() : null,
        shippedAt: order.shippedAt ? order.shippedAt.toISOString() : null,
        deliveredAt: order.deliveredAt ? order.deliveredAt.toISOString() : null,
        cancelledAt: order.cancelledAt ? order.cancelledAt.toISOString() : null,
        returnedAt: order.returnedAt ? order.returnedAt.toISOString() : null,
        createdAt: order.createdAt.toISOString(),
        updatedAt: order.updatedAt.toISOString(),
        deletedAt: order.deletedAt ? order.deletedAt.toISOString() : null,
        items: order.items ? order.items.map(toItemLineDto) : [],
    };
}

export function toOrderDetailResponse(order: OrderDomain): OrderDetailResponseDto {
    const base = toOrderListItemDto(order);
    
    const addresses: OrderDetailAddressDto[] = (order.addresses || []).map(addr => ({
        id: addr.id,
        orderId: addr.orderId,
        addressType: addr.addressType,
        recipientName: addr.recipientName,
        phoneNumber: addr.phoneNumber,
        addressLine1: addr.addressLine1,
        addressLine2: addr.addressLine2,
        landmark: addr.landmark,
        city: addr.city,
        district: addr.district,
        state: addr.state,
        postalCode: addr.postalCode,
        country: addr.country,
        latitude: addr.latitude !== null ? addr.latitude.toString() : null,
        longitude: addr.longitude !== null ? addr.longitude.toString() : null,
        deliveryNotes: addr.deliveryNotes,
        createdAt: addr.createdAt.toISOString(),
    }));

    const history: OrderDetailHistoryDto[] = (order.history || []).map(h => ({
        id: h.id,
        orderId: h.orderId,
        sellerId: h.sellerId,
        changedByUserId: h.changedByUserId,
        fromStatus: h.fromStatus,
        toStatus: h.toStatus,
        action: h.action,
        source: h.source,
        result: h.result,
        reason: h.reason,
        remarks: h.remarks,
        referenceId: h.referenceId,
        ipAddress: h.ipAddress,
        userAgent: h.userAgent,
        changedAt: h.changedAt.toISOString(),
        createdAt: h.createdAt.toISOString(),
    }));

    const payments: OrderDetailPaymentDto[] = (order.payments || []).map(p => ({
        id: p.id,
        orderId: p.orderId,
        sellerId: p.sellerId,
        paymentNumber: p.paymentNumber,
        paymentStatus: p.paymentStatus,
        paymentMethod: p.paymentMethod,
        paymentGateway: p.paymentGateway,
        currency: p.currency,
        amount: p.amount.toFixed(2),
        gatewayFee: p.gatewayFee !== null ? p.gatewayFee.toFixed(2) : null,
        platformFee: p.platformFee !== null ? p.platformFee.toFixed(2) : null,
        taxAmount: p.taxAmount !== null ? p.taxAmount.toFixed(2) : null,
        netAmount: p.netAmount.toFixed(2),
        transactionId: p.transactionId,
        gatewayPaymentId: p.gatewayPaymentId,
        gatewayOrderId: p.gatewayOrderId,
        gatewayReferenceId: p.gatewayReferenceId,
        gatewaySignature: p.gatewaySignature,
        initiatedAt: p.initiatedAt ? p.initiatedAt.toISOString() : null,
        authorizedAt: p.authorizedAt ? p.authorizedAt.toISOString() : null,
        paidAt: p.paidAt ? p.paidAt.toISOString() : null,
        capturedAt: p.capturedAt ? p.capturedAt.toISOString() : null,
        failedAt: p.failedAt ? p.failedAt.toISOString() : null,
        cancelledAt: p.cancelledAt ? p.cancelledAt.toISOString() : null,
        expiredAt: p.expiredAt ? p.expiredAt.toISOString() : null,
        payerName: p.payerName,
        payerEmail: p.payerEmail,
        payerPhone: p.payerPhone,
        failureReason: p.failureReason,
        gatewayResponse: p.gatewayResponse,
        notes: p.notes,
        internalNotes: p.internalNotes,
        createdAt: p.createdAt.toISOString(),
        updatedAt: p.updatedAt.toISOString(),
        deletedAt: p.deletedAt ? p.deletedAt.toISOString() : null,
    }));

    return {
        ...base,
        addresses,
        history,
        payments,
    };
}
