import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/modules/auth/components/auth-provider";
import NavbarView from "@/modules/Navbar/view/navbar-view";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Needlon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Added pt-28 (Desktop default) to body to keep elements from starting at absolute 0 under your fixed nav */}
      <body className="min-h-full flex flex-col pt-28 md:pt-9 ">
        <AuthProvider>
          <NavbarView />
          <main className="flex-1 w-full">{children}</main>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
