// ============================================================================
// Needlon
// Messages Module
// File: db/schema/messages/message-attachments/metadata.ts
// Description:
// JSON metadata stored alongside a message attachment.
//
// This metadata contains provider-specific information, processing details,
// previews, and business references that do not require dedicated columns.
// ============================================================================

/**
 * ============================================================================
 * Message Attachment Metadata
 * ============================================================================
 */
export interface MessageAttachmentMetadata {
    /**
     * Optional image width.
     */
    width?: number | null;

    /**
     * Optional image/video height.
     */
    height?: number | null;

    /**
     * Optional video/audio duration
     * in seconds.
     */
    duration?: number | null;

    /**
     * Optional video frame rate.
     */
    frameRate?: number | null;

    /**
     * Optional bitrate.
     */
    bitrate?: number | null;

    /**
     * Optional image/video thumbnail URL.
     */
    thumbnailUrl?: string | null;

    /**
     * Blur placeholder used for
     * progressive image loading.
     */
    blurDataUrl?: string | null;

    /**
     * Preview URL generated by
     * the storage provider.
     */
    previewUrl?: string | null;

    /**
     * Public download URL.
     */
    downloadUrl?: string | null;

    /**
     * Original upload source.
     *
     * Example:
     * Camera
     * Gallery
     * Files
     */
    source?: string | null;

    /**
     * Optional OCR extracted text.
     */
    extractedText?: string | null;

    /**
     * Virus scan status.
     */
    virusScanStatus?:
        | "PENDING"
        | "PASSED"
        | "FAILED";

    /**
     * Image moderation status.
     */
    moderationStatus?:
        | "PENDING"
        | "APPROVED"
        | "REJECTED";

    /**
     * Whether preview generation
     * has completed.
     */
    previewGenerated?: boolean;

    /**
     * Product reference when sharing
     * a product card.
     */
    productId?: string | null;

    /**
     * Order reference when sharing
     * an order card.
     */
    orderId?: string | null;

    /**
     * Invoice reference.
     */
    invoiceId?: string | null;

    /**
     * Manifest reference.
     */
    manifestId?: string | null;

    /**
     * Provider-specific metadata.
     *
     * Example:
     * Supabase object metadata,
     * S3 metadata, etc.
     */
    providerMetadata?: Record<
        string,
        unknown
    >;
}