// ============================================================================
// Needlon
// Messages Module
// File: db/schema/messages/message-reactions/metadata.ts
// Description:
// JSON metadata stored for a message reaction.
//
// This metadata stores device information, synchronization details,
// analytics and client-specific data that do not require dedicated columns.
// ============================================================================

/**
 * ============================================================================
 * Message Reaction Metadata
 * ============================================================================
 */
export interface MessageReactionMetadata {
    /**
     * Device identifier.
     */
    deviceId?: string | null;

    /**
     * Device name.
     *
     * Example:
     * iPhone 16 Pro
     * Chrome on Windows
     */
    deviceName?: string | null;

    /**
     * Operating system.
     *
     * Example:
     * Windows
     * Android
     * iOS
     */
    operatingSystem?: string | null;

    /**
     * Browser name.
     *
     * Example:
     * Chrome
     * Safari
     * Firefox
     */
    browser?: string | null;

    /**
     * Browser version.
     */
    browserVersion?: string | null;

    /**
     * Session identifier.
     */
    sessionId?: string | null;

    /**
     * IP address from which
     * the reaction originated.
     */
    ipAddress?: string | null;

    /**
     * User agent string.
     */
    userAgent?: string | null;

    /**
     * Source of the reaction.
     */
    source?:
        | "WEB"
        | "ANDROID"
        | "IOS"
        | "DESKTOP"
        | "SYSTEM";

    /**
     * Synchronization status
     * across user devices.
     */
    syncStatus?:
        | "PENDING"
        | "SYNCED"
        | "FAILED";

    /**
     * Timestamp when this
     * reaction was synchronized.
     *
     * ISO-8601 format.
     */
    syncedAt?: string | null;

    /**
     * Network latency in milliseconds.
     */
    latencyMs?: number | null;

    /**
     * Whether this reaction
     * was created while offline.
     */
    offlineCreated?: boolean;

    /**
     * Client application version.
     */
    appVersion?: string | null;

    /**
     * Whether this reaction
     * was generated by the system.
     */
    systemGenerated?: boolean;

    /**
     * Provider-specific metadata.
     */
    providerMetadata?: Record<
        string,
        unknown
    >;
}